#!/usr/bin/env bash
#
# build_appimage.sh — build a native Linux AppImage of Space Station Explorer.
#
# Produces a single, portable, double-clickable SpaceStationExplorer-x86_64.AppImage
# that bundles Python, tkinter and matplotlib. No system Python needed to run it.
#
# Usage:   ./build_appimage.sh
# Output:  dist/SpaceStationExplorer-x86_64.AppImage
#
# Requirements to BUILD (not to run the result):
#   - python3 (3.6+) with the tkinter system package available
#       Debian/Ubuntu:  sudo apt install python3-tk
#       Fedora:         sudo dnf install python3-tkinter
#   - internet access on first run (to fetch appimagetool)
#   - FUSE, or the script falls back to --appimage-extract-and-run
#
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"          # -> Code/
ROOT="$PWD"
APP="SpaceStationExplorer"
ARCH="$(uname -m)"
PY="${PYTHON:-python3}"

echo ">> [1/6] Checking build prerequisites..."
if ! "$PY" -c "import tkinter" 2>/dev/null; then
    echo "ERROR: python3 tkinter is not available."
    echo "       Install it (e.g. 'sudo apt install python3-tk') and re-run."
    exit 1
fi

echo ">> [2/6] Creating build virtualenv (.buildvenv)..."
# --system-site-packages so the venv can see the system tkinter (tkinter can't
# be pip-installed; it ships with the OS Python).
"$PY" -m venv --system-site-packages .buildvenv
VPY=".buildvenv/bin/python"
"$VPY" -m pip install -q --upgrade pip
"$VPY" -m pip install -q -r requirements.txt

echo ">> [3/6] Generating PyInstaller spec and building the binary (onedir)..."
cat > "${APP}.linux.spec" <<'SPEC'
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_appimage.sh — native Linux (onedir) build.

block_cipher = None

a = Analysis(
    ['linux_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[('game/*.py', 'game')],
    hiddenimports=[
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'game.main', 'game.special_rooms', 'game.stock_market',
        'game.items', 'game.quarters', 'game.character_creation', 'game.game',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name='SpaceStationExplorer',
    debug=False, strip=False, upx=False,
    console=False,          # windowed (GUI) app
)
coll = COLLECT(
    exe, a.binaries, a.zipfiles, a.datas,
    strip=False, upx=False, name='SpaceStationExplorer',
)
SPEC

"$VPY" -m PyInstaller --noconfirm --clean "${APP}.linux.spec"

echo ">> [4/6] Assembling AppDir..."
APPDIR="build/${APP}.AppDir"
rm -rf "$APPDIR"
mkdir -p "$APPDIR/usr/bin"
cp -a "dist/${APP}/." "$APPDIR/usr/bin/"
install -m 755 packaging/linux/AppRun "$APPDIR/AppRun"
cp packaging/linux/${APP}.desktop "$APPDIR/${APP}.desktop"
cp packaging/linux/space_station_icon.png "$APPDIR/space_station_icon.png"
cp packaging/linux/space_station_icon.png "$APPDIR/.DirIcon"

echo ">> [5/6] Fetching appimagetool if needed..."
TOOL="build/appimagetool-${ARCH}.AppImage"
if [ ! -x "$TOOL" ]; then
    curl -sSL -o "$TOOL" \
        "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${ARCH}.AppImage"
    chmod +x "$TOOL"
fi

echo ">> [6/6] Building the AppImage..."
OUT="dist/${APP}-${ARCH}.AppImage"
# Try FUSE first; fall back to extract-and-run in FUSE-less environments (CI).
if ! ARCH="$ARCH" "$TOOL" "$APPDIR" "$OUT" 2>/dev/null; then
    ARCH="$ARCH" "$TOOL" --appimage-extract-and-run "$APPDIR" "$OUT"
fi
chmod +x "$OUT"

echo
echo "Done -> $OUT"
echo "Run it with:  ./$OUT     (saves go to ~/.local/share/SpaceStationExplorer)"
